// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFiHpnKkSitnM_ROX6FZ8l7lsHKWF-4s',
    appId: '1:615602429310:android:2e6f890d03bee64bca272f',
    messagingSenderId: '615602429310',
    projectId: 'sayyarte-f6029',
    storageBucket: 'sayyarte-f6029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlR-NJLWjg9dQLDmjj24I2Nf-4frcBXN0',
    appId: '1:615602429310:ios:9bb2c3bb4c4eb1d7ca272f',
    messagingSenderId: '615602429310',
    projectId: 'sayyarte-f6029',
    storageBucket: 'sayyarte-f6029.appspot.com',
    androidClientId: '615602429310-l48onbf746usu536djoggks148kh0n6s.apps.googleusercontent.com',
    iosClientId: '615602429310-nnataehkbb42fgjehiubt35q2fcboji6.apps.googleusercontent.com',
    iosBundleId: 'com.tintix.saudia.tintiApp',
  );
}
